name: scan
on:
  push:
    branches:
    - main
  pull_request:
jobs:
  build:
    name: Scan
    runs-on: ubuntu-24.04
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Generate tarball from image
      run: |
        docker pull api7/api7-ee-3-gateway:3.8.5
        docker save -o vuln-image.tar api7/api7-ee-3-gateway:3.8.5

    - name: Run Trivy vulnerability scanner in tarball mode
      uses: aquasecurity/trivy-action@0.28.0
      with:
        input: /github/workspace/vuln-image.tar
        severity: 'CRITICAL,HIGH'
